CREATE DATABASE Test
USE Test

CREATE TABLE Persons (
	PersonId INT IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	Salary DECIMAL(8,2) NOT NULL,
	PassportID INT NOT NULL
)

ALTER TABLE Persons
ADD PRIMARY KEY (PersonID)

INSERT INTO Persons(FirstName,Salary,PassportID)
VALUES
	('Roberto',43300.00,102),
	('Tom',56100.00,103),
	('Yana',60200.00,101)

CREATE TABLE Passports(
	PassportId INT IDENTITY(101,1) PRIMARY KEY,
	PassportNumber NVARCHAR(8) NOT NULL
)


INSERT INTO Passports(PassportNumber)
VALUES
	('N34FG21B'),
	('K65LO4R7'),
	('ZE657QP2')

ALTER TABLE Persons
ADD CONSTRAINT FK_UserPassportId FOREIGN KEY (PassportId)
REFERENCES Passports(PassportId)