CREATE TABLE Orders (
	OrderID INT NOT NULL,
	CustomerID INT NOT NULL
)

CREATE TABLE Customers (
	CustomerID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE,
	CityID INT NOT NULL
)

CREATE TABLE Cities (
	CityID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE OrderItems (
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
)

CREATE TABLE Items (
	ItemID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL
)

CREATE TABLE ItemTypes (
	ItemTypeID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL
)

ALTER TABLE Cities
ADD PRIMARY KEY (CityID)

ALTER TABLE Customers
ADD PRIMARY KEY (CustomerID),
CONSTRAINT FK_CityIDKey FOREIGN KEY (CityID) REFERENCES Cities(CityID)

ALTER TABLE Orders
ADD PRIMARY KEY (OrderID),
CONSTRAINT FK_CustID FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)

ALTER TABLE ItemTypes
ADD PRIMARY KEY (ItemTypeID)
 
ALTER TABLE Items
ADD PRIMARY KEY (ItemID),
CONSTRAINT FK_ItemTypeID FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)

ALTER TABLE OrderItems
ADD PRIMARY KEY (OrderID,ItemID),
CONSTRAINT FK_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
CONSTRAINT FK_ItemID FOREIGN KEY (ItemID) REFERENCES Items(ItemID)