CREATE DATABASE SoftUni
USE SoftUni
CREATE TABLE Towns(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Addresses(
	Id INT PRIMARY KEY IDENTITY,
	AddressText NVARCHAR(100) NOT NULL,
	TownId INT NOT NULL
	FOREIGN KEY (TownId) REFERENCES Towns(Id)
)

CREATE TABLE Departments(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Employees(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	MiddleName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	JobTitle NVARCHAR(100) NOT NULL,
	DepartmentId INT NOT NULL,
	HireDate DATE NOT NULL,
	Salary DECIMAL(7,2),
	AddressId INT NOT NULL
	FOREIGN KEY (DepartmentId) REFERENCES Departments(Id),
	FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
)

BACKUP DATABASE [SoftUni] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MISHAKAVELI\MSSQL\Backup\SoftUni.bak' WITH NOFORMAT, NOINIT,  NAME = N'SoftUni-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
